### ISSUE TITLE
Unable to run migrations from scratch

### ISSUE THREAD

**Issue by DusanMadar** [jazzband/django-constance#229]
### The problem
I have a project with 50+ migrations in it and recently decided I want to use Constance for a couple of settings.

Everything was OK while developing/adding dynamic settings. I guess it's due to the fact that I setup the Constance config first, did the migration and only then start to use dynamic settings values.

Although when I want to do a test deploy  (i.e. when starting up a new Vagrant VM) and run all the migrations from scratch it fails. I am unable to run `python manage.py migrate database`, `python manage.py migrate` or even `python manage.py showmigrations`.

```
  File "/vagrant/my_app/views.py", line 138, in MyViewSet
    my_variable = constance_config.MY_VARIABLE
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/utils/functional.py", line 239, in inner
    return func(self._wrapped, *args)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/constance/base.py", line 19, in __getattr__
    result = self._backend.get(key)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/constance/backends/database/__init__.py", line 74, in get
    value = self._model._default_manager.get(key=key).value
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/.virtualenvs/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "constance_config" does not exist
LINE 1: ...ce_config"."key", "constance_config"."value" FROM "constance...
```
So a table that is about to be created is referenced already.

### System configuration

* Django version: 1.11.3
* Python version: 3.5.2,

**Comment by not-much-io** [comment]
Same issue as here?: https://github.com/jazzband/django-constance/issues/227

Haven't gotten around to trying commenting out the imports one by one as this doesn't seem like a real solution..

**Comment by DusanMadar** [comment]
I was to get around it doing this:
```
def get_constance_setting(setting):
    """
    A dirty workaround to enable Constance do the inital migration and not
    fail because the table that is about to be created doesn't exist yet.

    @setting (str) setting to retrieve

    @returns given setting value
    """
    try:
        return getattr(constance_config, setting)
    except ProgrammingError as exc:
        if str(exc).startswith('relation "constance_config" does not exist'):
            # TODO logging a waring message wouldn't hurt.
            pass
        else:
            raise exc

```

**Comment by camilonova** [comment]
Please check with master if the last pull request fixes this problem.

**Comment by jundymek** [comment]
> I was able to get around it doing this:
Where should I put this code (in which file)? I get an error: 
`django.db.utils.ProgrammingError: (1146, "Table 'testowa.constance_config' doesn't exist")`

**Comment by camilonova** [comment]
@jundymek you should install from master branch and give it a try.

**Comment by jundymek** [comment]
> @jundymek you should install from master branch and give it a try.

I copied backends/database/__init__.py but it didn't help. I am trying to switch database from sqlite to mysql. When I use sqlite everything is ok - python manage.py migrate works normal. When I try to change database (to mysql) error appears. This is a part of my settings.py:
```
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'testowa',
        'USER': 'testowy',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}
```
Sorry for my bad English.

**Comment by DusanMadar** [comment]
@camilonova the problem persists.

Installed with
```
-e git+https://github.com/jazzband/django-constance.git@5ec5ac79913b45b1489be67c5a9a951dbe22a6a4#egg=django-constance[database]
```

**Comment by camilonova** [comment]
@khchine5 would you like to take a look?

**Comment by camilonova** [comment]
@whs would you like to take a look?

**Comment by whs** [comment]
Please list

- The command if you're using (migrate? test? custom?)
- The stack trace, or if it's exactly the same as OP please state so
- Your Django and Python version.
- I assume that you're running in MySQL. Is it mysqlclient or other client?
- Also please remove the workaround above if you're using it

I only tested my PR with Postgres and SQLite. I'll try to reproduce the issue.

**Comment by whs** [comment]
I just tested migration with Python 3.6.2 (Arch), Django 1.11.4, MariaDB 10.2.7 (Docker) and the migration run just fine.

**Comment by jundymek** [comment]
I use Python 3.5.2, Django 1.10.5, mysql (mysqlclient). Any command with python manage.py throws 
`django.db.utils.ProgrammingError: (1146, "Table 'testowa.constance_config' doesn't exist")`
error.

**Comment by whs** [comment]
Could you paste the whole stack trace?

ProgrammingError was supposed to be caught, as it was added in the commit f8aad0c7f628cbc031e44c20709c9928971c515f

**Comment by jundymek** [comment]
What is stack trace? Is it a whole error code? Sorry - it is fault of my poor english...

**Comment by whs** [comment]
Yes, the whole error, or you can just paste the whole output from `python manage.py migrate`

For example you can see the big code block in the original issue filing.

**Comment by jundymek** [comment]
This is my whole error code:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\apps\config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\jundymek\Envs\katalog\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\Dropbox\PYTHON\NAUKA\nauka_DJANG\katalog\mainapp\models.py", line 92, in <module>
    class Site(models.Model):
  File "D:\Dropbox\PYTHON\NAUKA\nauka_DJANG\katalog\mainapp\models.py", line 101, in Site
    name = models.CharField(max_length=config.TITLE_LENGTH_MAX, verbose_name="Tytuł")
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\utils\functional.py", line 235, in inner
    return func(self._wrapped, *args)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\constance\base.py", line 22, in __getattr__
    setattr(self, key, default)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\constance\base.py", line 29, in __setattr__
    self._backend.set(key, value)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\constance\backends\database\__init__.py", line 86, in set
    key=self.add_prefix(key), defaults={'value': value}
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\query.py", line 473, in get_or_create
    return self.get(**lookup), False
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\query.py", line 379, in get
    num = len(clone)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\query.py", line 238, in __len__
    self._fetch_all()
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\models\sql\compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\mysql\base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\connections.py", line 292, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'testowa.constance_config' doesn't exist")
```

**Comment by whs** [comment]
Hmm, I didn't expect a default setattr in https://github.com/jazzband/django-constance/blob/master/constance/base.py#L22 .

I intentionally didn't supported attribute setting without a database, as discussed in the pull request. It make your whole app semi-usable without a database and the user may not realize that it is in semi-broken state.

With that setattr I suppose adding try..except in `set` couldn't be avoided and the user have to use Django system check to see that they have pending validation instead.

Or, would it be better to remove that setattr? (Pinging @camilonova)

@jundymek , I believe you have `None` as the the default value of `TITLE_LENGTH_MAX`. If you change all constance default values to something else but `None` then it should be working.

However, I don't think it is possible to use dynamic config value as a `CharField` attribute. `max_length` is enforced by the database server, which is set by Django upon table creation. You will need to makemigrations/migrate every time this value changes instead of just on the fly changes.

A better solution would be writing custom [clean](https://docs.djangoproject.com/en/1.11/ref/models/instances/#django.db.models.Model.clean), or set [validators](https://docs.djangoproject.com/en/1.11/ref/forms/validation/#validators) attribute on a field.

**Comment by DusanMadar** [comment]
@whs Here's what my system specs are.

- The command if you're using (migrate? test? custom?)
  - `python manage.py showmigrations`
- The stack trace, or if it's exactly the same as OP please state so
  - same as OP
- Your Django and Python version.
  - Django 1.11.3
  - Python 3.5.2
- I assume that you're running in MySQL. Is it mysqlclient or other client?
 - psql (PostgreSQL) 9.5.7

**Comment by jundymek** [comment]
> I believe you have None as the the default value of TITLE_LENGTH_MAX. If you change all constance default values to something else but None then it should be working.

No I don't. There is no None as the default value of any setting. TITLE_LENGTH_MAX default value is 30.

**Comment by whs** [comment]
With a lack of further discussion, I decided to go with let `set` run while database is not initialized.

Could one of you please test from [my master](https://github.com/whs/django-constance) whether it solve your problem before I submit a PR. (If it does, please keep this issue open until it is merged.)

**Comment by jundymek** [comment]
...
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\migrations\operations\fields.py", line 84, in database_forwards
    field,
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\mysql\schema.py", line 43, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\base\schema.py", line 409, in add_field
    self.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\base\schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\django\db\backends\mysql\base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 247, in execute
    res = self._query(query)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\cursors.py", line 374, in _do_query
    db.query(q)
  File "C:\Users\jundymek\Envs\katalog\lib\site-packages\MySQLdb\connections.py", line 292, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1067, "Invalid default value for 'gender'")
```
I don't have any 'gender' value in my Constance settings.

**Comment by whs** [comment]
That's an error in your application, unrelated to constance. The constance source also have no reference to `gender`. Without full source to your application I can't troubleshoot it further (and I suppose StackOverflow would be more fitting for that).

**Comment by DusanMadar** [comment]
@whs your fix works. I am able to run migrations from scratch, use `python manage.py showmigrations`, etc.

Installed with `pip install -r requirements.txt` and with this line added to `requirements.txt`:

-e git+https://github.com/whs/django-constance.git@0e38ae7ce1da2691480d96926784982ea13ae278#egg=django-constance[database]

**Comment by camilonova** [comment]
@whs Thank you.

**Comment by mikeengland** [comment]
I am experiencing another issue where constance is somehow locking the sqllite table when running Django tests. Has anyone else encountered this? `django.db.utils.OperationalError: database table is locked`
