### ISSUE TITLE
Setting a constance setting in a test aborts the current transaction

### ISSUE THREAD

**Issue by surfer190** [jazzband/django-constance#292]
### Describe the problem

I am changing constance settings in a TestCase (with a postgres database). When I do this an error is raised.

```
from constance import config as constance_settings

class EntryTests(TestCase):
    def test_calculate_duration_fifteen_minutes(self):
        '''Ensure the duration rounds to 15 minutes when set'''
        constance_settings.TIMECAPTURE_INTERVAL_MINUTES = 15
        ...
```

the error:

`django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block `

### Steps to reproduce

1. Use the postgreSQL database 9.6
2. Add constance to your project
3. Add a constance setting called `TIMECAPTURE_INTERVAL_MINUTES`
4. In the `setUp` method of the `TestCase` set the constance setting `TIMECAPTURE_INTERVAL_MINUTES` to 0
5. Write a test that changes that constance setting at the start of the test to 15.
6. Run the Test

### Stacktrace

```
======================================================================
ERROR: test_calcaulate_duration_fifteen_minutes (entries.tests.test_models.EntryTests)
Ensure the duration rounds to 15 minutes when set
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stephen/projects/kid_hr_project/entries/tests/test_models.py", line 31, in setUp
    constance_settings.TIMECAPTURE_INTERVAL_MINUTES = 0
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/utils/functional.py", line 269, in __setattr__
    setattr(self._wrapped, name, value)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/constance/base.py", line 29, in __setattr__
    self._backend.set(key, value)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/constance/backends/database/__init__.py", line 88, in set
    key=self.add_prefix(key), defaults={'value': value}
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/stephen/projects/kid_hr_project/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block
```

Which goes looks like it arises from:

```
    def set(self, key, value):
        old_value = self.get(key)

        try:
            constance, created = self._model._default_manager.get_or_create(
                key=self.add_prefix(key), defaults={'value': value}
            )
        except (OperationalError, ProgrammingError):
            # database is not created, noop
            return
```

### System configuration

* Django version: 1.11.9
* Python version: 3.6.2
* Database: PostgreSQL 9.6
* Singificant packages: `django_tenent_schemas`

**Comment by DmitryKaramin** [comment]
Just a simple test
What am i doing wrong?


```python
from django.test import TestCase
from constance import config


class CalculatorTestCase(TestCase):
    def test_calculator(self):
        self.assertEqual(0, config.CALL_COST)
```

# Traseback
```
Testing started at 17:17 ...
/Users/dmitrykaramin/python37/bin/python3.7 "/Users/dmitrykaramin/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.7141.48/PyCharm.app/Contents/helpers/pycharm/django_test_manage.py" test apps.client.tests.test_calculator.CalculatorTestCase /Users/dmitrykaramin/backend/src
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

Error
Traceback (most recent call last):
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dmitrykaramin/backend/src/apps/client/tests/test_calculator.py", line 8, in test_calculator
    self.assertEqual(0, config.CALL_COST)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/constance/base.py", line 22, in __getattr__
    setattr(self, key, default)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/constance/base.py", line 29, in __setattr__
    self._backend.set(key, value)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/constance/backends/database/__init__.py", line 84, in set
    old_value = self.get(key)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/constance/backends/database/__init__.py", line 75, in get
    value = self._model._default_manager.get(key=key).value
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/dmitrykaramin/python37/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block


Destroying test database for alias 'default'...

Process finished with exit code 1
```
