### ISSUE TITLE
Django-constance not properly working with django 2.1

### ISSUE THREAD

**Issue by mitshel** [jazzband/django-constance#294]
### Describe the problem
Command line manage command of Django-constance not properly working with django 2.1

### Steps to reproduce
`./manage.py constance list`

result is error:
```
Traceback (most recent call last):
  File "D:\Мои документы\Dropbox\Projects\Eclipse\workspace\sopds\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Projects\Eclipse\workspace\sopds\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\Projects\Eclipse\workspace\sopds\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Projects\Eclipse\workspace\sopds\venv\lib\site-packages\django\core\management\base.py", line 308, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "D:\Projects\Eclipse\workspace\sopds\venv\lib\site-packages\django\core\management\base.py", line 282, in create_parser
    self.add_arguments(parser)
  File "D:\Projects\Eclipse\workspace\sopds\venv\lib\site-packages\constance\management\commands\constance.py", line 35, in add_arguments
    parser_list = subparsers.add_parser('list', cmd=self, help='list all Constance keys and their values')
  File "C:\Users\mitsh\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1116, in add_parser
    parser = self._parser_class(**kwargs)
  File "D:\Projects\Eclipse\workspace\sopds\venv\lib\site-packages\django\core\management\base.py", line 48, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'cmd'
```

### System configuration

* Django version: 2.1
* Python version: 3.5-3.7

**Comment by jryannel** [comment]
Seems to be this line:
```
        parser_list = subparsers.add_parser('list', cmd=self, help='list all Constance keys and their values')
```

And following lines using cmd argument. Removing the "cmd" argument makes it work again.

I could not find a reference in ArgumentParser add_prser for the cmd parameter. Need to check the git log

**Comment by rahulsoni11** [comment]
I'm Beginner in Django, 
Can I still be able to use Constance in my Django 2.1 Project, if yes How.?

**Comment by mitshel** [comment]
Download django-constance from master branch from GITHUB and use it.

**Comment by camilonova** [comment]
@mitshel please confirm if this issue is fixed and close it, next I can release a new version.
