### ISSUE TITLE
Use `gettext` in CONSTANCE_CONFIG_FIELDSETS

### ISSUE THREAD

**Issue by pauk-slon** [jazzband/django-constance#306]
I'd like to use fieldsets in the Constance section on the Django admin site and have localized titles for its. Below, I will give an example where I will show that a common Django approach (which is usage of the function `gettext`) is impossible.

Let's say we have the following configuration in our settings.py

```
from django.utils.translation import ugettext_lazy as _

...

CONSTANCE_CONFIG_FIELDSETS = {
    _('Meal Cards'): (
        'BREAKFAST_DEFAULT_IMAGE',
        'LUNCH_DEFAULT_IMAGE',
        'DINNER_DEFAULT_IMAGE',
        'SNACK_DEFAULT_IMAGE',
    ),
}
```

In this case we will get an exception:

```
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/app/my_project/settings.py", line 376, in <module>
    'SNACK_DEFAULT_IMAGE',
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 151, in __hash__
    return hash(self.__cast())
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 126, in __cast
    return self.__text_cast()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 114, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 85, in ugettext
    return _trans.ugettext(message)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 321, in ugettext
    return do_translate(message, 'ugettext')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 298, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 205, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 114, in __init__
    self._add_installed_apps_translations()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 155, in _add_installed_apps_translations
    "The translation infrastructure cannot be initialized before the "
django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
```

As `_('Meal Cards')` is a key of a dictionary, it should be hashed and the lazy function `ugettext_lazy` should be evaluated immediately.

Could you add a support of a tuple for `CONSTANCE_CONFIG_FIELDSETS`? Like this:

```
CONSTANCE_CONFIG_FIELDSETS = (
    (_('Meal Cards'): (
        'BREAKFAST_DEFAULT_IMAGE',
        'LUNCH_DEFAULT_IMAGE',
        'DINNER_DEFAULT_IMAGE',
        'SNACK_DEFAULT_IMAGE',
    )),
)
```

### System configuration

* Django version: 1.9.2
* Python version: 2.7

**Comment by zodman** [comment]
i this kind of scenary you must use ugettext_lazy  because the gettext machinary its not loaded at settings.py
