### ISSUE TITLE
python manage.py runserver

### ISSUE THREAD

**Issue by Bhupendra89** [jazzband/django-constance#330]
### Describe the problem

Tell us about the problem you're having

### Steps to reproduce

Tell us how to reproduce it

### System configuration

* Django version:
* Python version:

**Comment by Bhupendra89** [comment]
C:\Users\Bhupendra\Desktop\mydjango>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\urls\resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\urls\resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\urls\resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Bhupendra\Desktop\mydjango\mydjango\urls.py", line 21, in <module>
    path('blog/', include('blog.url')),
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'blog.url'

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 585, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 570, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 288, in run
    self.run_loop()
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 294, in run_loop
    next(ticker)
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 334, in tick
    for filepath, mtime in self.snapshot_files():
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 350, in snapshot_files
    for file in self.watched_files():
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 249, in watched_files
    yield from iter_all_python_module_files()
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 103, in iter_all_python_module_files
    return iter_modules_and_files(modules, frozenset(_error_files))
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 136, in iter_modules_and_files
    if not path.exists():
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1339, in exists
    self.stat()
  File "C:\Users\Bhupendra\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1161, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>

**Comment by Bhupendra89** [comment]
python 3.7.3
django 2.2.2

**Comment by Bhupendra89** [comment]
python manage.py runserver 
not working properly what should I do

**Comment by camilonova** [comment]
You have a different problem in you project. From reading your traceback you can see `ModuleNotFoundError: No module named 'blog.url'`

**Comment by naveenkumargit99** [comment]
@camilonova Could you please let me know what was the fix you did. Thanks!

**Comment by naveenkumargit99** [comment]
@Bhupendra89 Could you please let us know the fix you did for this!!

**Comment by Dewrshi** [comment]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Dewarshi\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Dewarshi\PycharmProjects\djangoProject1\Pyshop\Pyshop\urls.py", line 21, in <module>
    path('products/', include(products.urls)),
NameError: name 'products' is not defined


# how to fix this shit

**Comment by sethipriyanshu** [comment]
I face the same issue ! Did you find a fix?

**Comment by santoshdc1** [comment]
PS C:\Users\ACER\Desktop\BusBook-main\busbook> python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\__init__.py", line 16, in setup
    from django.urls import set_script_prefix
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\__init__.py", line 1, in <module>
    from .base import (
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\exceptions.py", line 1, in <module>
    from django.http import Http404
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\__init__.py", line 2, in <module>
    from django.http.request import (
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\request.py", line 9, in <module>
    from django.core import signing
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\signing.py", line 43, in <module>
    from django.utils.crypto import constant_time_compare, salted_hmac
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\crypto.py", line 9, in <module>
    from django.utils.encoding import force_bytes
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\encoding.py", line 8, in <module>
    from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from partially initialized module 'django.utils.encoding' (most likely due to a circular import) (C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\encoding.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ACER\Desktop\BusBook-main\busbook\manage.py", line 22, in <module>
    main()
  File "C:\Users\ACER\Desktop\BusBook-main\busbook\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 411, in execute
    _parser = self.fetch_command("runserver").create_parser(
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 48, in load_command_class
    module = import_module("%s.management.commands.%s" % (app_name, name))
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\commands\runserver.py", line 10, in <module>
    from django.core.servers.basehttp import WSGIServer, get_internal_wsgi_application, run
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\servers\basehttp.py", line 17, in <module>
    from django.core.handlers.wsgi import LimitedStream
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\wsgi.py", line 5, in <module>
    from django.core.handlers import base
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 11, in <module>
    from django.urls import get_resolver, set_urlconf
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\__init__.py", line 1, in <module>
    from .base import (
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\exceptions.py", line 1, in <module>
    from django.http import Http404
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\__init__.py", line 2, in <module>
    from django.http.request import (
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\http\request.py", line 9, in <module>
    from django.core import signing
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\signing.py", line 43, in <module>
    from django.utils.crypto import constant_time_compare, salted_hmac
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\crypto.py", line 9, in <module>
    from django.utils.encoding import force_bytes
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\encoding.py", line 8, in <module>
    from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from partially initialized module 'django.utils.encoding' (most likely due to a circular import) (C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\encoding.py)]
