### ISSUE TITLE
exception in thread django-main-thread error

### ISSUE THREAD

**Issue by narenpop** [jazzband/django-constance#419]
### Describe the problem
<img width="659" alt="django_err" src="https://user-images.githubusercontent.com/50550350/91635911-ff81cc80-ea19-11ea-8d9f-63fd062da808.PNG">

Tell us about the problem you're having.

I was trying to install djangorestframewok and i installed it then i had an issue running the server have attached the image file

(localdev-EUbEEbsi) C:\Users\ASUS\Desktop\localdev\ecom>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\asus\appdata\local\programs\python\python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ASUS\.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ASUS\.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\ASUS\.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\management\base.py", line 392, in check
    all_issues = checks.run_checks(
  File "C:\Users\ASUS\.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\ASUS\.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\checks\urls.py", line 101, in check_url_settings
    if value and not value.endswith('/'):
AttributeError: 'tuple' object has no attribute 'endswith'

### Steps to reproduce

Tell us how to reproduce it.

### System configuration

* Django version:
* Python version:3.8.5
* Django-Constance version:

**Comment by Intergalaxen** [comment]
> ### Describe the problem
> <img alt="django_err" width="659" src="https://user-images.githubusercontent.com/50550350/91635911-ff81cc80-ea19-11ea-8d9f-63fd062da808.PNG">
> 
> Tell us about the problem you're having.
> 
> I was trying to install djangorestframewok and i installed it then i had an issue running the server have attached the image file
> 
> (localdev-EUbEEbsi) C:\Users\ASUS\Desktop\localdev\ecom>python manage.py runserver
> Watching for file changes with StatReloader
> Performing system checks...
> 
> Exception in thread django-main-thread:
> Traceback (most recent call last):
> File "c:\users\asus\appdata\local\programs\python\python38-32\lib\threading.py", line 932, in _bootstrap_inner
> self.run()
> File "c:\users\asus\appdata\local\programs\python\python38-32\lib\threading.py", line 870, in run
> self._target(*self._args, **self._kwargs)
> File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
> fn(*args, **kwargs)
> File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
> self.check(display_num_errors=True)
> File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\management\base.py", line 392, in check
> all_issues = checks.run_checks(
> File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
> new_errors = check(app_configs=app_configs, databases=databases)
> File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\checks\urls.py", line 101, in check_url_settings
> if value and not value.endswith('/'):
> AttributeError: 'tuple' object has no attribute 'endswith'
> 
> ### Steps to reproduce
> Tell us how to reproduce it.
> 
> ### System configuration
> * Django version:
> * Python version:3.8.5
> * Django-Constance version:

I'm having the same issue, have u been able to fix it? If yes, how did you make it? 
 /Int ^^

**Comment by Chuckpy** [comment]
Same as mine

**Comment by alphaion** [comment]
getting same error but didn't get any solution yet. :-(

**Comment by 2019980006** [comment]
same as  mine

**Comment by MuhammadNaseerAslam** [comment]
same as mine can anyone help please

**Comment by Mogost** [comment]
> "same as mine"

Doesn't help to understand your issue at all. 
Why do you think that the problem is with this library?  There is no one mention of django-constance in stacktrace.

**Comment by vbonh** [comment]
For those who are facing a similar problem and land on this page.

Go to your settings.py and make sure you have a coma at the end of each lines in your installed apps, Middleware etc...

Worked for me

**Comment by nganphtgit** [comment]
I got this error cause the space in each url, let check your syntax and the error message in the ending line

**Comment by Charlie5DH** [comment]
If you have this problem, go to the `settings.py` file, and check for comas and if `rest_framework` is correctly spelled.

**Comment by AkshatPatel07** [comment]
@vbonh can you please elaborate more. Facing same problem

**Comment by Aastha-1008** [comment]
@AkshatPatel07 Are you able to solve this error?

**Comment by kwonjaeyong1** [comment]
same as mine

**Comment by AkshatPatel07** [comment]
> @AkshatPatel07 Are you able to solve this error?

Yess

**Comment by command09** [comment]
same as mine can anyone help please

**Comment by command09** [comment]
use command Python manage.py migrate

**Comment by command09** [comment]
Python manage.py migrate

**Comment by naseeraslam** [comment]
I solved the problem by just installing required packages.

**Comment by JyotsanaMehra** [comment]
I was also facing the same issue. If you are not using any databases, then go to settings.py and comment out the Database section
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

This will resolve the issue

**Comment by Zaza2215** [comment]
I ran cmd as administrator and  everything worked.

**Comment by 2100031431** [comment]
same issue for me and i have checked the settings.py it was perfect

**Comment by LnPaulin** [comment]
Having working on windows and when i take my app to linux, I have that issue.. everything works file on windows but when I pull it from windows to linux and run any manage.py command I have the same issue you raised on this.. any ideas ?

**Comment by Sushant0999** [comment]
I was having the same issue.
I solved it by just changing the python interpreter.
Worked for me ✔.

**Comment by Statesonbrown** [comment]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\core\management\base.py", line 396, in check
    databases=databases,
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\urls\resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\urls\resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\django\urls\resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Z\Desktop\Attendance-System-Using-Face-Recognition\attendance_system_facial_recognition\urls.py", line 19, in <module>
    from recognition import views as recog_views
  File "C:\Users\Z\Desktop\Attendance-System-Using-Face-Recognition\recognition\views.py", line 18, in <module>
    from sklearn.preprocessing import LabelEncoder
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\__init__.py", line 76, in <module>
    from .base import clone
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\utils\__init__.py", line 13, in <module>
    from scipy.sparse import issparse
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\Z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by Lizano16** [comment]
PS C:\Users\Usuario\OneDrive\Escritorio\libreria\sistema> python manage.py runserver 
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper        
    fn(*args, **kwargs)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks 
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver 
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\functional.py", line 57, in __get__        
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns    
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\functional.py", line 57, in __get__        
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module  
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\OneDrive\Escritorio\libreria\sistema\sistema\urls.py", line 24, in <module>
    path('', include('chatbot.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\OneDrive\Escritorio\libreria\sistema\chatbot\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\Usuario\OneDrive\Escritorio\libreria\sistema\chatbot\views.py", line 5, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
PS C:\Users\Usuario\OneDrive\Escritorio\libreria\sistema> 

Alguien sabe por que me aparece este error

**Comment by mehdi8554** [comment]
For me solved as below:
pip unistall djangorestframework
pip install djangorestframework
that's all

**Comment by Himi-Deb** [comment]
> ### Describe the problem
> <img alt="django_err" width="659" src="https://user-images.githubusercontent.com/50550350/91635911-ff81cc80-ea19-11ea-8d9f-63fd062da808.PNG">
> 
> Tell us about the problem you're having.
> 
> I was trying to install djangorestframewok and i installed it then i had an issue running the server have attached the image file
> 
> (localdev-EUbEEbsi) C:\Users\ASUS\Desktop\localdev\ecom>python manage.py runserver Watching for file changes with StatReloader Performing system checks...
> 
> Exception in thread django-main-thread: Traceback (most recent call last): File "c:\users\asus\appdata\local\programs\python\python38-32\lib\threading.py", line 932, in _bootstrap_inner self.run() File "c:\users\asus\appdata\local\programs\python\python38-32\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper fn(*args, **kwargs) File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run self.check(display_num_errors=True) File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\management\base.py", line 392, in check all_issues = checks.run_checks( File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks new_errors = check(app_configs=app_configs, databases=databases) File "C:\Users\ASUS.virtualenvs\localdev-EUbEEbsi\lib\site-packages\django\core\checks\urls.py", line 101, in check_url_settings if value and not value.endswith('/'): AttributeError: 'tuple' object has no attribute 'endswith'
> 
> ### Steps to reproduce
> Tell us how to reproduce it.
> 
> ### System configuration
> * Django version:
> * Python version:3.8.5
> * Django-Constance version:


**I went to an earlier local version in vscode (undo on the recently deleted file)... which I am guess threw off this** 

"Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)"
    

Checked my settings.py but don't notice anything unusual

**Comment by Bhaktims** [comment]
i updated the pip using command "python.exe -m pip install --upgrade pip" and then reinstalled django

**Comment by 1Athar** [comment]
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\urls\resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Atharva\Desktop\PBL-SE\backend\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module    
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked 
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module     
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Atharva\Desktop\PBL-SE\captcha\captcha\urls.py", line 19, in <module>
    from . import views
ImportError: cannot import name 'views' from 'captcha' (C:\Users\Atharva\Desktop\PBL-SE\captcha\captcha\__init__.py)

I am getting this error please someone help...

**Comment by harsh4245** [comment]
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\dell\Downloads\trulyexpensesyoutube-master> py manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(self._args and self._kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 127, in inner_run      
    threading = options["use_threading"]
                ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'use_threading'

**Comment by dorian-404** [comment]
hey i have the same issue , did you solve it?

**Comment by Bhaktims** [comment]
> i updated the pip using command "python.exe -m pip install --upgrade pip" and then reinstalled Django.. and my Django is properly working.

**Comment by aniceto-jolela** [comment]
same as mine.

![Screenshot from 2024-07-08 17-22-21](https://github.com/jazzband/django-constance/assets/79465134/efd97251-8dc8-4dcd-a532-6b9694d17768)

![Screenshot from 2024-07-08 17-22-46](https://github.com/jazzband/django-constance/assets/79465134/6976fa64-0802-4bf3-97ce-44b6df3f114a)

**But, i gonna solve it.**

**Comment by aniceto-jolela** [comment]
**I already solved this basic error.**
Access this repository. You will find all steps to solve it.
👇👇👇
[django-main-thread](https://github.com/aniceto-jolela/bugs-fixed/blob/main/django/django-main-thread.md)
