### ISSUE TITLE
Exception in thread django-main-thread:

### ISSUE THREAD

**Issue by GSK002** [jazzband/django-constance#471]
### Describe the problem

Tell us about the problem you're having.

### Steps to reproduce

Tell us how to reproduce it.

### System configuration

* Django version:
* Python version:
* Django-Constance version:
* Django-rest_framework
C:\Users\Asian paints\Desktop\note\Scripts\myproject>python manage.py runserver       
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper  
    fn(*args, **kwargs)
  File "D:\Python\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "D:\Python\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "D:\Python\lib\site-packages\django\core\management\__init__.py", line 375, in 
execute
    autoreload.check_errors(django.setup)()
  File "D:\Python\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper  
    fn(*args, **kwargs)
  File "D:\Python\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Python\lib\site-packages\django\apps\registry.py", line 91, in populate    
    app_config = AppConfig.create(entry)
  File "D:\Python\lib\site-packages\django\apps\config.py", line 224, in create       
    import_module(entry)
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_frameworkwebapp'

**Comment by GSK002** [comment]
please help me solve problem

**Comment by Mogost** [comment]
This problem is not related to the django-constance, judging from the description.
