### ISSUE TITLE
'Options' object has no attribute 'installed'

### ISSUE THREAD

**Issue by amigold** [jazzband/django-constance#495]
### Describe the problem

When migrating to Django 4.1 and running `manage.py migratae` I get this error:

Traceback (most recent call last):
  File "/Users/somewhere/server/webserver/code/FareFlyWebServer/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 376, in handle
    emit_post_migrate_signal(
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/somewhere/server/venv/lib/python3.9/site-packages/constance/apps.py", line 27, in create_perm
    if ContentType._meta.installed and Permission._meta.installed:
AttributeError: 'Options' object has no attribute 'installed'

Even if I try to run a --fake migration it won't work

### System configuration

* Django version: 4.1
* Python version: 3.9
* Django-Constance version: 2.9.0

**Comment by VandaFarsad** [comment]
There is a fix on the master branch which has not received a release tag yet. You can use that until a new release is available.

**Comment by amigold** [comment]
Thanks @VandaFarsad !

**Comment by camilonova** [comment]
Duplicated of #493
