### ISSUE TITLE
KeyError on constance after changing cache to PyMemcacheCache

### ISSUE THREAD

**Issue by SasivimolB** [jazzband/django-constance#517]
### Describe the problem
After updating memcache backend to use PyMemcacheCache instead of MemcachedCache, I got KeyError on my store's constance from pymemcache.

```
2023-04-10 15:58:52   Traceback (most recent call last):
2023-04-10 15:58:52   File "/application/src/oscar_prime/core/context_processors.py", line 45, in metadata
2023-04-10 15:58:52     constance_context = get_constance_global_context()
2023-04-10 15:58:52   File "/application/src/oscar_prime/core/utils.py", line 163, in get_constance_global_context
2023-04-10 15:58:52     context['store'] = Store()
2023-04-10 15:58:52   File "/application/src/oscar_prime/core/context/store.py", line 16, in _init_
2023-04-10 15:58:52     self.address = Address()
2023-04-10 15:58:52   File "/application/src/oscar_prime/core/context/address.py", line 8, in _init_
2023-04-10 15:58:52     self.city = config.store_address_city
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/django/utils/functional.py", line 247, in inner
2023-04-10 15:58:52     return func(self._wrapped, *args)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/constance/base.py", line 19, in _getattr_
2023-04-10 15:58:52     result = self._backend.get(key)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/constance/backends/database/_init_.py", line 72, in get
2023-04-10 15:58:52     value = self._cache.get(key)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/django/core/cache/backends/memcached.py", line 77, in get
2023-04-10 15:58:52     return self._cache.get(key, default)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/pymemcache/client/hash.py", line 347, in get
2023-04-10 15:58:52     return self._run_cmd("get", key, default, default=default, **kwargs)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
2023-04-10 15:58:52     return self._safely_run_func(client, func, default_val, *args, **kwargs)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/pymemcache/client/hash.py", line 211, in _safely_run_func
2023-04-10 15:58:52     result = func(*args, **kwargs)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/newrelic/api/datastore_trace.py", line 162, in _nr_datastore_trace_wrapper_
2023-04-10 15:58:52     return wrapped(*args, **kwargs)
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/pymemcache/client/base.py", line 687, in get
2023-04-10 15:58:52     return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/pymemcache/client/base.py", line 1153, in _fetch_cmd
2023-04-10 15:58:52     key, value, buf = self._extract_value(
2023-04-10 15:58:52   File "/appenv/lib/python3.8/site-packages/pymemcache/client/base.py", line 1107, in _extract_value
2023-04-10 15:58:52     original_key = remapped_keys[key]
2023-04-10 15:58:52 KeyError: b'sandbox:local:1:shop_logo'

```
This is my cache config:
```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': os.getenv('MEMCACHED_HOST'),
        'KEY_PREFIX': "",
        'KEY_FUNCTION': 'django_tenants.cache.make_key',
        'REVERSE_KEY_FUNCTION': 'django_tenants.cache.reverse_key',
    }
}
```

### Steps to reproduce
I only change from MemcachedCache to PyMemcacheCache, start a project and this error appears.

### System configuration

* Django version: 3.2.18
* Python version: 3.8.10
* Django-Constance version: 2.8.0

**Comment by thran** [comment]
I encounter same problem.
It is probably [threading issue in PyMemcacheCache](https://groups.google.com/g/django-updates/c/MKFg-BctkS0). 

I solved it by setting
```
     "OPTIONS": {
          "use_pooling": True,
      },
```
in CACHE settings. I only hope, that it solve the problem completlly. Another option is use redis cache.

**Comment by SasivimolB** [comment]
Thanks! Adding `"use_pooling": True` solved the problem

**Comment by thran** [comment]
Happy to help, I have fix in production and it seems solid.
