### ISSUE TITLE
"no such table: constance_config" when running test suite

### ISSUE THREAD

**Issue by pcraig3** [jazzband/django-constance#575]
### Describe the problem

Recently, I upgraded constance from `3.1.0` to `4.0.1` in my Django project, which has gone fine. I ran the migrations and we were all set. Functionally, we are all good: it works like it did before, no issues.

However, when running my test command `python manage.py test`, I started to get this error from Django constance.

```
➜  poetry run python manage.py test

Found 452 test(s).
Creating test database for alias 'default'...
copy data from old constance table to a new one
Traceback (most recent call last):

copy data from old constance table to a new one
Traceback (most recent call last):
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: constance_config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/constance/migrations/0002_migrate_from_old_table.py", line 19, in _migrate_from_old_table
    cursor.execute(
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paul/Library/Caches/pypoetry/virtualenvs/bloom-nofos-ztRUj9S3-py3.11/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: constance_config

System check identified no issues (0 silenced).
......................................................................................................
......................................................................................................
......................................................................................................
......................................................................................................
............................................
----------------------------------------------------------------------
Ran 452 tests in 1.056s

OK
Destroying test database for alias 'default'...
```

So it does actually run the tests and nothing is failing. But obviously getting a huge error message like that before all the tests run is really annoying.

It seems to be happening by running migrations automatically when creating a disposable test database. It looks to me like the culprit is [`"0002_migrate_from_old_table.py", line 19`](https://github.com/jazzband/django-constance/blob/master/constance/migrations/0002_migrate_from_old_table.py#L19) where we look for the table  "constance_config" and don't find it. 

To be clear, I am not actually testing constance or mocking any values, it's just that the tests automatically are running these migrations every time I run my test suite.

To get rid of the stack trace, I have added this to my `settings.py` which prevents running constance migrations during tests.

```
# Disable migrations for constance in tests because there is a bug in their migration file
if "test" in sys.argv or "test_coverage" in sys.argv:
    MIGRATION_MODULES = {
        "constance": None,
    }
```

If there is some other way to address this, I am all ears.

### System configuration

* Django version: `5.0.8`
* Python version: `3.11.9`
* Django-Constance version: `4.0.1`

**Comment by Mogost** [comment]
I have no idea how this is connected to the django-constance 4.x release.
The code you linked comes from #469. And this is from 3.x release.

@sergei-iurchenko what could have caused this?

**Comment by sebastianmanger** [comment]
It is caused by the mentioned PR, and not tied to release 4.x. Data is migrated from `constance_config` to `constance_constance` in migration `0002_migrate_from_old_table`. The exception is only logged, and properly handled (as stated - the current state is functional).

The migration logs an error as `FROM constance_config` fails on fresh databases, as the database name is [not stated anymore](https://github.com/jazzband/django-constance/pull/469/files#diff-4ac35cfdc3d5cedad47cd6dc4597a980369d6320f9a60919bb5fd224bf1f3602R12)/not created. I monkey-patched the function with this fully untested snippet:

```
def _migrate_from_old_table(apps, schema_editor) -> None:
    """
    Copies values from old table.
    On new installations just ignore error that table does not exist.
    """
    connection = schema_editor.connection
    quoted_string = ', '.join([connection.ops.quote_name(item) for item in ['id', 'key', 'value']])
    if 'constance_config' in connection.introspection.table_names():
        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    f'INSERT INTO constance_constance ( {quoted_string} ) SELECT {quoted_string} FROM constance_config',  # noqa: S608
                    [],
                )
                cursor.execute('DROP TABLE constance_config', [])
        except DatabaseError:
            logger.exception('copy data from old constance table to a new one')

    Constance = apps.get_model('constance', 'Constance')
    sequence_sql = connection.ops.sequence_reset_sql(no_style(), [Constance])
    with connection.cursor() as cursor:
        for sql in sequence_sql:
            cursor.execute(sql)
```

**Comment by sergei-iurchenko** [comment]
Hello) This is expected correct behaviour. We can do nothing with it to preserve backwards compatibility.
I have to 2 ideas to make it a bit less verbose:
1) configure logging to suppress error messages from this module
2) Configure migrate to False in DATABASES https://docs.djangoproject.com/en/5.0/ref/settings/#migrate to create tables in tests by models not by migrations
